### ISSUE TITLE
JIRA 6.x compatiblity

### ISSUE THREAD

**Issue by martinmalek** [mteodori/jira-git-plugin#7]
It would be nice to get this to work with JIRA 6.x

We managed to connect to our gitlab server but the output is not pretty.

**Comment by therealprof** [comment]
The subversion plugin has the same problem. See:
https://answers.atlassian.com/questions/173511/when-will-the-jira-subversion-plugin-be-available-for-version-6
for a workaround

**Comment by martinmalek** [comment]
Thanks therealprof

If the fix is as easy as commenting out disable_html_escaping() or similar it shouldn't be any issues releasing a JIRA 6.x compatible version.

**Comment by therealprof** [comment]
#disable_html_escaping()
needs to be inserted in both the issue and project panel templates. I've verified that this works.

Just not sure what this will do to <6.0 compatibility.

**Comment by jpwalters** [comment]
I'm having the same Jira 6.x formatting issue with git as well.  

therealprof,  can you either post your code or tell me where to insert #disable_html_escaping() in the template files so that I can fix installation?

**Comment by jpwalters** [comment]
I added the #disable_html_escaping() line to the top of each xml template, update the jar file BUT I didn't restart Jira.  Once I restarted Jira the formatting issues is now resolved.  Thanks guys for the fix.

**Comment by martinmalek** [comment]
Still. A release with the patch applied for 6.x is the way to go instead of having everyone monkey pathcing their installations.

**Comment by mteodori** [comment]
pull request anyone?
